version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:latest

commands:
  restore_modules:
    steps:
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
  save_modules:
    steps:
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run: npm install
      - run: npm run build
      - run:
          name: Test module
          command: npm run test
      - save_modules
    
  test:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run:
          name: Test module
          command: npm run test

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
          