version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test

workflows:
  main:
    jobs:
      - build  
